[labels]
scores = "A:A"
ages = "B:B"

[formula]
total_scores = "sum(scores)"
avg_age = "sum(ages)/count(ages)"

[data]
grid = [
  [ 5, 25, "total_scores:", "" ],
  [ 1, 21, "avg_age:", "" ],
  [ 3, 23 ],
  [ 4, 20 ],
  [ 9, 19 ],
]
