[labels]
scores = "A:A"
ages = "B:B"

[formula]
total_scores = "sum(scores)"
total_age = "sum(ages)"
avg_age = "total_age/5"

[data]
grid = [
  [ 5, 25, "total_scores:", "" ],
  [ 1, 21, "total_age:",    "" ],
  [ 3, 23, "avg_age:" ],
  [ 4, 20 ],
  [ 9, 19 ],
]
