[labels]
scores = "A:A"
ages = "B:B"

[formula]
total_scores = "sum(scores)"
avg_age = "sum(ages)/count(ages)"

[data]
grid = [
  # A  B   C                D
  [ 5, 25, "total_scores:", 22   ], # 1
  [ 1, 21, "avg_age:",      21.6 ], # 2
  [ 3, 23, "",              ""   ], # 3
  [ 4, 20, "",              ""   ], # 4
  [ 9, 19, "",              ""   ], # 5
]
